### PR TITLE
Dynk mod energy

### PR DESCRIPTION
**Pull request by Pingul**
DYNK GLOBAL-VARS

### CODE REVIEW

**Comment by kyrsjo** [comment]
TODO:
 * Manual (Doc/user_manual/six.tex) - only commit the .tex file for now
 * Add SixTest test (I'll show you! It's easy.)
 * Run SixTest tests.
 * Code review (there is already a TODO for sanity check, and I would like to also check that there is no element "GLOBAL-VARS")

Just before the merge (but not before!), we shall add your name to the "hall of fame" on the top of the sixtrack.s and commit the .pdf.

Please do not commit anything large to this branch, unless really needed (i.e. SixTest canonicals)...

**Comment by Pingul** [comment]
Great! I'll hunt you down a little later to discuss the testing. Thank you for your help!

**Comment by Pingul** [comment]
I added a small entry in the table you showed, please read through and advise. I was contemplating writing some more to explain what it does, but I wasn't sure where best to put it if so. Would it be best to create a new section? Or is it fine as it is?

**Comment by kyrsjo** [comment]
Hi Joel, I sent you a Pull Request: https://github.com/Pingul/SixTrack/pull/1
If you accept this, it will update this branch with the changes I proposed. After this I consider the manual to be finished.

The only thing remaining is for you to write two small input sanity checks where there are TODOs in the code (the first should be a small `if` checking if idp or ition are 0 -- look just beneath the `call dynk_pretrack` in `trauthin` and `trauthck` where it decides wether to call 4d or 6d tracking; the second should be a `if element_name == GLOBAL_VARS`).

The tests we do together. If you already have a fort.2 and fort.3 we can use a modified version of that.

Please don't leave this 80% finished!

**Comment by Pingul** [comment]
Perfect, thanks! I had not thought about the potential name-collision; I'll push a fix.

I was awaiting feedback before continuing with the tests, and I knew you had a lot on your plate with HL-LHC. I am available this week to work on the tests if you have the time. I have working fort.2/3 files for both normal and collimation version readily available.

**Comment by kyrsjo** [comment]
Perfect, the "normal" version is what is good for a test; collimation version is never exactly reproducible due to lack of both CRLIBM and paranthesis.

Once you've pushed the fix for the two TODOs and it has been reviewed, we can sit together to add the test. Then you can add your name to the license block, bump the date (I usually collect a few features for each version bump), and merge!

**Comment by Pingul** [comment]
I've made a push to the repo with a version that compiles and run. I tried to figure out how to run SixTrack in 4d-tracking mode and how to add an element to fort.2, but I didn't find what I was looking for in the manual. Please advise.

**Comment by kyrsjo** [comment]
Very good!

Did you test it, i.e. did you see that it catches a GLOBAL-VARS element in the single element list if DYNK is on (and lets it pass if it is off, as described in the manual)?

For 4D tracking, try to remove the cavities (kz=12) from fort.2 or set their voltage to 0.0, and remove the SYNC block from fort.3. There are also some 4d tests in SixTest which you may use as a starting point...

Let's do the SixTest tomorrow afternoon, does that work for you?

**Comment by Pingul** [comment]
Hmm... Embarrassing -- the indentation is inconsistently wrong. All `+if` is throwing my eyes off guard :) I'll amend the commit with a correct version tomorrow.

Okay great, I'll try that approach! I'm available all afternoon. I could come down at, say, 16?

**Comment by kyrsjo** [comment]
Don't amend the commit, just make a new commit with the 1 character fix.

A proper editor [1] should be able to take care of the indenting automatically (except for the ASTUCE stuff...); you should be able to just hit "TAB" and the machine should do the rest.

[1]: Obviously, "a proper editor" refers to the one true editor - EMACS by Saint IGNUcius :neckbeard: ;)

**Comment by Pingul** [comment]
I did not put enough faith in the all mighty and sublime Sublime™ God, and so I didn't trust the power of the "TAB". Updated with a small fix now.

(The main indentation should be correct now, but the output string indentation seems a little inconsistent in the code. I used 4 indentation depth for output strings, but that number seems to be varying.)

**Comment by kyrsjo** [comment]
Great!

Yeah, it's not really consistent. I try to make it more or less consistent within the same piece of code...

At least there is no \t tabs... See Silicon Valley S03E06 -- tabs vs spaces and vim vs emacs :)

**Comment by Pingul** [comment]
Now it should be working! I included the changes we discussed, and added a 'dynk_globalvars' folder by default.

**Comment by kyrsjo** [comment]
Perfect! Can I ask you to do one more thing:
 * Merge from upstream/master into your branch
 * Bump the date in the top of sixtrack.s
 * Add your name to the list of names just below sixtrack.s

Thanks!

**Comment by Pingul** [comment]
Done. For some reason the merge did not do a fast-forward, but otherwise I hope everything should be fine.

Thank you for your help!

**Comment by kyrsjo** [comment]
That looks perfect! A merge from a different branch who has had commits should not be a fast forward, so this is as expected.

Thanks!

**Pull request merged**
