### PR TITLE
Revert "BDEX: Beam Distribution EXchange"

### PR DESCRIPTION
**Pull request by rdemaria**
Reverts SixTrack/SixTrack#67

### CODE REVIEW

**Comment by kyrsjo** [comment]
Thanks. BDEX isn't finish, and I'll rather polish up pipefun first ( #66 ), then merge that to master, merge master to BDEX, then finish BDEX, and finally merge BDEX to pipefun...

**Comment by kyrsjo** [comment]
Was this what you did to create this pull request?

https://help.github.com/articles/reverting-a-pull-request/

**Comment by rdemaria** [comment]
Probably, my internet connection is not very sane at the moment...

On Thu, May 19, 2016 at 2:47 PM, Kyrre Ness Sjøbæk <notifications@github.com

**Comment by kyrsjo** [comment]
OK, I'll merge this then, then recreate #67 .

**Pull request merged**
