### PR TITLE
BDEX

### PR DESCRIPTION
**Pull request by kyrsjo**
As described in issue #59 , this patch allows exchanging the particle distribution at some element.

TODO:
- Binary format in order to avoid roundoff errors, or at least CRLIBM (if not already there?)
- Documentation
- More than just thin6d tracking (this could also be implemented in a later patch)?
- Testing...

Related development: DYNK-PIPEFUN, pull request #66 .

Please don't merge this yet, I'll rather avoid a repeat of #67 and #68  :)

### CODE REVIEW

**Comment by kyrsjo** [comment]
OK, the main functionality is now all there. To test, I will modify the SixTest tests to add BDEX somewhere, then couple it with bdex_echo.py. The results should be unchanged both in the case of sending nparticles=-1 (no change) and replaying the particle distribution. This will also exersise CRLIBM's decimal<->binary conversion quite a bit...

**Comment by kyrsjo** [comment]
Features to add:
 * Configuration `NOSTOP` - don't stop tracking even if all particles are lost - there may be new particles coming at the next BDEX element
 * While running, telling SixTrack to stop

**Comment by kyrsjo** [comment]
More features to add:
 * Collimation support!
 * Storing bunches *internally*, in allocatable tables, so that the command from the "controller" ca be just "switch to bank 1", "store current bunch in bank 2" etc.

**Comment by kyrsjo** [comment]
Ideas: extra headers:
 * After initializing pipe, write information about sub-protocol: `collimation`, dropping energy variables except `ejv` and `sigmv`, value of`npart`, ... other things maybe needed for FLUKA coupling
 * For actions read- and write particles (at the ends of thick elements like drifts which represents collimators -- exchange happens at markers), write `dcum` or length since last write if we are now on a read (as seen by SixTrack), possibly taking the starting point into account.
 * Instead of writing out the full distribution, only write out the means.
 * With lost particles watch out for
```
              clo6v(1,jj)=clo6v(1,jj1)
              clo6v(2,jj)=clo6v(2,jj1)
              clo6v(3,jj)=clo6v(3,jj1)
              clop6v(1,jj)=clop6v(1,jj1)
              clop6v(2,jj)=clop6v(2,jj1)
              clop6v(3,jj)=clop6v(3,jj1)
!--beam-beam element
              di0xs(jj)=di0xs(jj1)
              dip0xs(jj)=dip0xs(jj1)
              di0zs(jj)=di0zs(jj1)
              dip0zs(jj)=dip0zs(jj1)
```
in `+cd lost4`!

**Comment by kyrsjo** [comment]
After more consideration and discussion with Alessio, trying to "swap bunches" may be a bit tricky to be sure is working 100% as the particle losses code in SixTrack is complicated, especially if we are trying to take care of all the cases like collimation. Furthermore, the tracking uses a LOT of extra "particle-arrays" which should then also be swapped out (and who knows what kind of dependencies that would drag along). Restricting it to *modifying* particles is therefore probably safer.

Using this, the coupling in https://github.com/apsimonr/matlab-beam-loading-llrf would need to be a bit rethought; one possibility would however be to track all the particles in one big train (using the z offset of each particle), then write everything to the pipe; slice into bunches and do crab kicks/LLRF on the non-SixTrack side, and then write them back to SixTrack for further tracking.

Regarding *adding* particles (from FLUKA etc), this may need a bit more thought. Hmm.

TODO: How does the collimation part work with "fat bunches" ? In this case we would be loading one big particle distribution as a single "packet"... We should also make sure that the particle arrays are at least as big as npart (and that they are some multiple of them)! Furthermore, if BDEX+COLLIMAT, number of packages should probably always be set to 1 (or the remote program should be notified when the turn number resets)...

**Comment by kyrsjo** [comment]
More "particle arrays": di0xs, di0zs, dip0xs, dip0zs -- these are handled in lostpart; `qwcs(:,1/2/3)`: Tunes, only used in fort.90 etc. headers, not handled in lostpart.

For collimation, This is the code for copying a sample *to* the  tracking arrays (in one place):
```
               do j = 1, napx
                 pstop(nlostp(j))=.false.
               enddo
               do j = 1, napx
                  xv(1,j)  = 1e3*myx(j)+torbx(1)
                  yv(1,j)  = 1e3*myxp(j)+torbxp(1)
                  xv(2,j)  = 1e3*myy(j)+torby(1)
                  yv(2,j)  = 1e3*myyp(j)+torbyp(1)
                  sigmv(j) = mys(j)
                  ejv(j)   = myp(j)
!hr03             ejfv(j)=sqrt(ejv(j)*ejv(j)-pma*pma)
                  ejfv(j)=sqrt(ejv(j)**2-pma**2)                         !hr03
                  rvv(j)=(ejv(j)*e0f)/(e0*ejfv(j))
                  dpsv(j)=(ejfv(j)-e0f)/e0f
                  oidpsv(j)=one/(one+dpsv(j))
!hr03             dpsv1(j)=dpsv(j)*c1e3*oidpsv(j)
                  dpsv1(j)=(dpsv(j)*c1e3)*oidpsv(j)                      !hr03
cc2008
                  namepart(j) = samplenumber*100 + j
cc2008
               enddo
           endif
```

The more general code:
```
            do i = 1, napx00
!hr08         xv(1,i)  = 1e3*myx(i+(j-1)*napx00)  +torbx(1)
!hr08         yv(1,i)  = 1e3*myxp(i+(j-1)*napx00) +torbxp(1)
!hr08         xv(2,i)  = 1e3*myy(i+(j-1)*napx00)  +torby(1)
!hr08         yv(2,i)  = 1e3*myyp(i+(j-1)*napx00) +torbyp(1)
              xv(1,i)  = 1d3*myx(i+(j-1)*napx00)  +torbx(1)              !hr08
              yv(1,i)  = 1d3*myxp(i+(j-1)*napx00) +torbxp(1)             !hr08
              xv(2,i)  = 1d3*myy(i+(j-1)*napx00)  +torby(1)              !hr08
              yv(2,i)  = 1d3*myyp(i+(j-1)*napx00) +torbyp(1)             !hr08
              x00(i)  = xv(1,i)
              xp00(i) = yv(1,i)
              y00(i)  = xv(2,i)
              yp00(i) = yv(2,i)
!JULY2005
!JULY2005 assignation of the proper bunch length
!              sigmv(i) = 0d0
              sigmv(i) = mys(i+(j-1)*napx00)
!JULY2005
!APRIL2005
!              ejv(i)   = myenom
              ejv(i)   = myp(i+(j-1)*napx00)
!
!GRD FOR NOT FAST TRACKING ONLY
!hr08         ejfv(i)=sqrt(ejv(i)*ejv(i)-pma*pma)
              ejfv(i)=sqrt(ejv(i)**2-pma**2)                             !hr08
              rvv(i)=(ejv(i)*e0f)/(e0*ejfv(i))
              dpsv(i)=(ejfv(i)-e0f)/e0f
              oidpsv(i)=one/(one+dpsv(i))
!hr08         dpsv1(i)=dpsv(i)*c1e3*oidpsv(i)
              dpsv1(i)=(dpsv(i)*c1e3)*oidpsv(i)                          !hr08
!GRD
!APRIL2005
!
!              dpsv(i)  = 0d0
              nlostp(i)=i
              do ieff =1, numeff
                 counted_r(i,ieff) = 0
                 counted_x(i,ieff) = 0
                 counted_y(i,ieff) = 0
	         do ieffdpop =1, numeffdpop
		    counted2d(i,ieff,ieffdpop) = 0
	         end do	
              end do
	      do ieffdpop =1, numeffdpop
                 counteddpop(i,ieffdpop) = 0
              end do

            end do
```

Note: In `dump_beam_population`, the index is given as follows: `nlostp(j)+(samplenumber-1)*npart` -- considering the rest of the collimation code, it may be more appropriate to use `napx00` than `npart`

**Comment by kyrsjo** [comment]
Regarding adding particles: As discussed in #251 , `al`, `as`, and `bl1v` are only used in thick tracking, and as long as there is no momentum variation they should be the same. I need to check that there are no other particle arrays that are used in thin tracking but not reshuffled...

**Comment by kyrsjo** [comment]
OK, now we're up to date with the latest tag; note that there are a few more versions.

The splitting off of DYNK apparently gave GIT some problems with the code churn, but careful merging of intermediate versions got me over that bump.

I'll continue once I (or someone else) has ran the "addtag" script to add tags and then written releases for the latest versions... But please have a chat with me before doing it, the way I'm doing it is a bit dangerous for the repository but it gets the tags right. Whoever deletes all our release notes get to type it in again.

**Comment by JamesMolson** [comment]
This has now been merged into the dev branch. Work will continue there.

**Comment by kyrsjo** [comment]
PR into the dev branch #391

**Pull request closed without merging**
