### PR TITLE
James mass pr testing

### PR DESCRIPTION
**Pull request by kyrsjo**
DO NOT ACTUALLY PULL THIS PR!

This branch contains PR #117  #118 #116 (in that order!) merged into master. Normal and CR binaries have been built with gfortran and ifort 2011. Will run tests over the weekend.

If everything passes:
In SixTrack.s of #117 :
 - Bump the date in the `+cd version` block
 - Add the name "J. Molson, LAL" to the `+cd license` block
Then merge #117 #118 #116 IN THIS ORDER, and kill this branch and PR.

### CODE REVIEW

**Comment by kyrsjo** [comment]
They seemed to have worked!

I'm really looking forward to the new "smart" test suite by the way... One which knows which tests are applicable to which binaries, and runs them automatically and in parallel.

**Comment by JamesMolson** [comment]
I need to clear the comments from the other files (not sixtrack.s) before you commit this. Give me 5 mins.

**Comment by kyrsjo** [comment]
Which files? dabnew?

Anyway, don't hurry I have to run for a meeting now, will look at your stuff again in a little over an hour.

**Comment by kyrsjo** [comment]
OK, so let's do it this way:
1. Merge #118 #116 . Before I do any of that, could you please merge from master to both of them, and THEN update date/license of ONE of them (the one to be merged first)?
2. I'll branch out from master, fix #120 - which is worthy of a version number bump - and merge the result to master.
3. Meanwhile, you do the rollback on #117 in order to fix the conflict. You then wait until point 2 (merge fix for #120 ) is complete, and then merge the then-current master (i.e. after I've merged #120) on top of what you have after the `git reset`. Then you fix the deleted normal comments in `dabnew.s`, we check CAREFULLY sixtrack.s for any similar problems, you then bump the version number and date (license update will come with the #116 or #118 which gets merged into master and then gets merged into #117 ). Then I will merge #117 to master.
4. Development continues as normally...

If unclear, I'll be available to talk (tomorrow)!

**Comment by kyrsjo** [comment]
All merged!

**Pull request closed without merging**
