### PR TITLE
Fix FMA problems

### PR DESCRIPTION
**Pull request by kyrsjo**
For fixing #138

### CODE REVIEW

**Comment by JamesMolson** [comment]
Do the tests still pass with complex*16 ?

**Comment by kyrsjo** [comment]
OK, now it passes the tests with both nagfor and gfortran. @JamesMolson , could you test 		a05e3e1 with 64-bit on LXPLUS?

However, nagfor found me something REALLY worrying: In subroutine ZFUN, which is used by TUNENEWT, we have the following statement:
```
+if crlibm
      ZTUNE1=EXP_RN((-ZU*DUEPI)*TUNEA1) !!! EXP_RN expects a DOUBLE PRECISION, not COMPLEX !!!
+ei
+if .not.crlibm
      ZTUNE1=EXP((-ZU*DUEPI)*TUNEA1)
+ei
```

Note the comment (my recent addition) - `DUEPI` is 2*pi, TUNEA1 is some real number (DOUBLE PRECISSION); but ZU is the imaginary unit: `ZU=DCMPLX(0D0,1D0)`...

From nagfor I get the following oh-shit-shit-shit warning:
` Warning: plato_seq.f: Argument 1 to EXP_RN has data type DOUBLE PRECISION in reference from TUNELASK and COMPLEX(KIND(0d0)) in reference from ZFUN `
I guess we could rewrite it as `ZTUNE1=cos_rn(DUEPI*TUNEA1) + ZU*sin_rn(DUEPI*TUNEA1)`? However, expect a change of the results from tunenewt (which must have been wrong before, when compiling with crlibm).

**Comment by kyrsjo** [comment]
The oh-shit warning was fixed. Tests are not affected.

It is still failing tunefft and tuneffti with nagfor tough... Very strange.

**Comment by JamesMolson** [comment]
Ok, so currently (with the above patches) on lxplus:
32 bit gfortran passes
64bit does not.

32bit nagfor also fails.
64 bit ifort fails.

All failures are in the fma_sixtrack file for the TUNEFFTI output.

Nagfor seems to get all the comparisons for TUNEFFTI as bad, but only some are bad for gfortran and ifort.


but, on my main desktop (fedora23) 64bit gfortran does pass okay.

**Comment by JamesMolson** [comment]
64 bit clang/gfortran on osx is good too.

**Comment by kyrsjo** [comment]
James: It should now work 100%. Nagfor/32 and gfortran/32 agrees on my machine (to a new .canonical), could you test gfortran/64 on LxPlus?

Miriam&James: Please review my changes. I think I fixed a few bugs (especially the "calling exp(real) as exp(complex)", that was a nasty one). Let me know when I can bump the date (and version number probably) and we merge.

**Pull request merged**
