### PR TITLE
Minor bug

### PR DESCRIPTION
**Pull request by vkbo**
aper_parseInputLine is now recursive and needs to be labelled as such.

### CODE REVIEW

**Comment by amereghe** [comment]
why?

**Comment by vkbo** [comment]
Because you changed the routines, and they now call each other. Therefore the compiler sees this as potentially recursive, even though it isn't in practice.

**Comment by amereghe** [comment]
oh - good catch! but why do we need to declare only one as recursive?

**Comment by vkbo** [comment]
Only when running Debug build with gfortran. It is a lot more picky and exits on this.

**Comment by vkbo** [comment]
Also, not so much a "good catch" as a red "failed" on the test build system :P

**Comment by amereghe** [comment]
ok, great, thanks

**Pull request merged**
