### PR TITLE
first quicktest commit

### PR DESCRIPTION
**Pull request by rdemaria**
Almost there for  #23. Using the make file for compiling. Off-course the first test fails..

### CODE REVIEW

**Comment by kyrsjo** [comment]
Is this dead?

**Comment by rdemaria** [comment]
I would say so the day we have ctest...

**Comment by kyrsjo** [comment]
OK, so when we merge #107 we can close this one?

**Comment by rdemaria** [comment]
Yes with pleasure...

**Comment by kyrsjo** [comment]
CTEST is merged -> QuickTest is dead, long live QuickTest. Hopefully, SixTest will soon follow.

**Pull request closed without merging**
