### PR TITLE
Update Sixin.zip for prob1/prob3 to remove RIPP block, which was removed in v4.5.20

### PR DESCRIPTION
**Pull request by kyrsjo**

### CODE REVIEW

**Comment by mfittere** [comment]
Didn't you want to remove the RIPP block???

**Comment by kyrsjo** [comment]
Hi Miriam,
yes the title "Update Sixin.zip for prob1/prob3 to include RIPP block, which was removed in v4.5.20" is a bit wrong...

I'll update it. Waiting for the tests to finish!

**Comment by mfittere** [comment]
Keep me posted!

**Comment by kyrsjo** [comment]
Let's merge this tomorrow when both your and my test has finished.

**Comment by mfittere** [comment]
What do you want me to test??? I thought Josch is doing the e-lens DYNK and I didn't have anything else on my list.

**Comment by kyrsjo** [comment]
In this case, *you == James. :)

**Comment by JamesMolson** [comment]
Linux:
```
1/2 Test #29: prob3 ............................   Passed  24308.41 sec
2/2 Test #28: prob1 ............................   Passed  25119.38 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
slow    = 49427.79 sec (2 tests)

Total Test time (real) = 25119.39 sec
```

**Comment by JamesMolson** [comment]
netbsd:
```
1/2 Test #29: prob3 ............................   Passed  26428.65 sec
2/2 Test #28: prob1 ............................   Passed  29112.67 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
slow    = 55541.32 sec (2 tests)

Total Test time (real) = 29112.72 sec
```

freebsd:
```
1/2 Test #29: prob3 ............................   Passed  28788.37 sec
2/2 Test #28: prob1 ............................   Passed  32016.87 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
slow    = 60805.24 sec (2 tests)

Total Test time (real) = 32016.88 sec
```

I guess merge when your osx run finishes.

**Comment by kyrsjo** [comment]
Mac OS X:
```
$ ctest -R prob -j2
Test project /Users/kyrsjo/code/SixTrack/SixTrack/SixTrack_cmakesix_API_BOINC_BUILD_TESTING_CR_LIBARCHIVE_defaultcompiler_defaultbuildtype
    Start 28: prob1
    Start 29: prob3
1/2 Test #29: prob3 ............................   Passed  25796.20 sec
2/2 Test #28: prob1 ............................   Passed  26783.50 sec

100% tests passed, 0 tests failed out of 2

Label Time Summary:
slow    = 52579.70 sec (2 tests)

Total Test time (real) = 26783.54 sec
```

I'll merge!

**Pull request merged**
