### PR TITLE
BDEX: Beam Distribution EXchange

### PR DESCRIPTION
**Pull request by kyrsjo**
As described in issue #59 , this patch allows exchanging the particle distribution at some element.

TODO:
- Binary format in order to avoid roundoff errors, or at least CRLIBM (if not already there?)
- Documentation
- More than just thin6d tracking (this could also be implemented in a later patch)?
- Testing...

Related development: DYNK-PIPEFUN, pull request #66 .

### CODE REVIEW

**Comment by kyrsjo** [comment]
Please don't merge this yet... Are you reversing it in #68 ?

**Comment by rdemaria** [comment]
yes, I have just wrote you an email, revert in #68 and re-open the pull
request... Sorry for the mess..

On Thu, May 19, 2016 at 2:42 PM, Kyrre Ness Sjøbæk <notifications@github.com

**Comment by kyrsjo** [comment]
Argh... I cannot create a new pull request, since "nothing has changed"...

Maybe if I commit something to the BDEX branch? I'll try to make a placeholder for the docs :)

**Comment by kyrsjo** [comment]
ArghArgh... That didn't really work:
https://github.com/SixTrack/SixTrack/compare/master...kyrsjo:BDEX

**Comment by kyrsjo** [comment]
Well, at least the code is back to where it was; comparing sixtrack.s in 3725cbcb333f9ad48e44f68d380c6bc443abb96f
and the current master HEAD
5a80dd9a210ef33545f2860067db6d54e473d0f3
with DIFF shows no differences, but diffing the current master HEAD with kyrsjo:BDEX shows the expected differences.

I'll try to ask GitHub support...

**Pull request merged**
