### PR TITLE
CMake changes for arm and osx

### PR DESCRIPTION
**Pull request by JamesMolson**

### CODE REVIEW

**Comment by vkbo** [comment]
Is the clang bit only valid for Apple, or can we have it as a general section?

**Comment by JamesMolson** [comment]
Apple only, normal clang explodes.

**Comment by vkbo** [comment]
COVERAGE and GPROF flags don't apply either I assume?

**Comment by JamesMolson** [comment]
gprof for sure not.

**Comment by vkbo** [comment]
Checked the documentation. The Coverage flags are fine, but -pg does not exist.

**Comment by JamesMolson** [comment]
um, they are not in the man pages

**Comment by vkbo** [comment]
https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fprofile-arcs

Assuming this is the correct documentation?

**Comment by JamesMolson** [comment]
ok, it does work, but the fortran part explodes with it enabled so I can't test it. -pg explodes.


AppleClang != Clang. They forked it a long time ago and have done terrible dark things to it since.

**Comment by vkbo** [comment]
Ah, I see. In that case.

**Comment by vkbo** [comment]
Could you please just delete the flags that do not apply? Commented out code that doesn't work anyway is just clutter ...

**Pull request merged**
