### PR TITLE
adding `#` char to header of aperture losses

### PR DESCRIPTION
**Pull request by amereghe**
The header of the aperture losses file does not have a char marking it is a header.
This may result in analysis tools not being able to correctly crunch the file - e.g. `np.loadtxt`.

### CODE REVIEW

**Comment by kyrsjo** [comment]
Is this also the case for some of the collimation files, or has this now been fixed? I have a vague memory of this being an issue in the past...

**Comment by amereghe** [comment]
mmm should check it, and I have to fix the tests, of course...
...running out of time... can we post-pone the BOINC release?

**Comment by vkbo** [comment]
> mmm should check it, and I have to fix the tests, of course...
> ...running out of time... can we post-pone the BOINC release?

I can push new canonicals, if that's all that's missing.

**Comment by vkbo** [comment]
Also: Please don't make any changes to files in collimation right now.

**Comment by vkbo** [comment]
> excellent, thanks a lot!
> Yes, I agree, let's wait to have the Collimation PRs in and then we check the format of the headers

Yes, I've been modifying a lot of them while going through the code. Many have issues with for instance assuming number of particles and turns is <= 9999.

**Pull request merged**
