### PR TITLE
Update lxplus detection and compiler + cmake paths with the lxplus flag.

### PR DESCRIPTION
**Pull request by JamesMolson**
This should hopefully fix an issue @amereghe was having.

Also the paths used for the lxplus flag were still pointing to sl6 versions.

Everything is updated to the latest now.

### CODE REVIEW

**Comment by rdemaria** [comment]
I understand it is better to check for lxplus explicitly instead of AFS/CVMFS because it forces the version of the compilers, right?

**Comment by JamesMolson** [comment]
It doesn't force the compiler version, but only tells you how to do it.

The previous method was freezing when it tried to access cvmfs on alessio's computer - /cvmfs/ existed and was mounted, but wasn't connected resulting in a potentially infinite time out.

**Comment by rdemaria** [comment]
ok for me

**Comment by amereghe** [comment]
I cannot merge :)

**Comment by amereghe** [comment]
just checked out the source branch, and it works perfectly on my machine.
Thanks for the fix, @JamesMolson

**Pull request merged**
