### PR TITLE
adding new style output with expert flag

### PR DESCRIPTION
**Pull request by rdemaria**

### CODE REVIEW

**Comment by kyrsjo** [comment]
Checking it now... It may be a good idea to just write this thing to a file instead of fort.6 / STDOUT...

**Comment by rdemaria** [comment]
I would not mind having it in a file, but I think this will be temporary, so maybe it is not worth investing too much

**Comment by kyrsjo** [comment]
Should be a pretty easy fix if I can find a safe UNIT. I'll do it after we've discussed the amp-stuff.

**Comment by kyrsjo** [comment]
Done. Also nice to see is that
`diff SixTest/beam-HO_LR-oldstyle/beam_expert.txt SixTest/beam-HO_LR-newstyle/beam_expert.txt`
shows that the files are identical :)
The file looks like:
```
/ ******* USING emitx= 0.335097E-03, emity= 0.335097E-03, emitz=  8.11204     ******
 bb_par.l5b1_18   0 2.4690512563437284e+000  5.9337539926380769e+000  24.342662050000001e+000  3.8389316030000000e-004  1.0000000000000000e+000
 bb_par.l5b1_17   0 2.5325436210963566e+000  6.2258132535999069e+000  25.456570480000000e+000  3.9312902200000000e-004  1.0000000000000000e+000
 bb_par.l5b1_16   0 2.6045001274614301e+000  6.5057053955634752e+000  26.017196980000001e+000  4.0177300239999998e-004  1.0000000000000000e+000
 bb_par.l5b1_15   0 3.0124290148106567e+000  6.0106999492413458e+000  26.151592940000000e+000  3.8609569500000002e-004  1.0000000000000000e+000
 bb_par.l5b1_14   0 4.0508843040262645e+000  4.5632791428378567e+000  25.900539670000001e+000  3.3632194289999999e-004  1.0000000000000000e+000
 bb_par.l5b1_13   0 5.5174056861510063e+000  3.0517713384496505e+000  25.557437289999999e+000  2.7493498820000003e-004  1.0000000000000000e+000
 bb_par.l5b1_12   0 6.4551186330154975e+000  2.1265959190474706e+000  24.942721190000000e+000  2.2937583060000000e-004  1.0000000000000000e+000
 bb_par.l5b1_11   0 6.3845158830189765e+000  1.6657512072050769e+000  23.802135600000000e+000  2.0284467420000001e-004  1.0000000000000000e+000
 bb_par.l5b1_10   0 5.6727512545683512e+000  1.4159801116067261e+000  22.263078600000000e+000  1.8683207410000001e-004  1.0000000000000000e+000
 bb_par.l5b1_9    0 4.1097896388940836e+000  1.4288171771336908e+000  20.081253990000000e+000  1.8746823560000000e-004  1.0000000000000000e+000
 bb_par.l5b1_8    0 2.5773232916394058e+000  1.5283998109665915e+000  17.708427940000000e+000  1.9368454090000001e-004  1.0000000000000000e+000
 bb_par.l5b1_7    0 1.6312627512681093e+000  1.4438850129344978e+000  15.448503060000000e+000  1.8805857370000000e-004  1.0000000000000000e+000
 bb_par.l5b1_6    0 1.1301823459889806e+000  1.1262369321956609e+000  13.239579940000000e+000  1.6589151829999999e-004  1.0000000000000000e+000
 bb_par.l5b1_5    0 7.8486473200560114e-001  7.8211963027134035e-001  11.032983440000001e+000  1.3801748309999999e-004  1.0000000000000000e+000
 bb_par.l5b1_4    0 5.0233200954427504e-001  5.0057013433233144e-001  8.8263869330000002e+000  1.1014344800000000e-004  1.0000000000000000e+000
 bb_par.l5b1_3    0 2.8258417860597712e-001  2.8158844438826092e-001  6.6197904279999999e+000  8.2269412789999998e-005  1.0000000000000000e+000
 bb_par.l5b1_2    0 1.2562123918558168e-001  1.2517456043791944e-001  4.4131939229999997e+000  5.4395377619999997e-005  1.0000000000000000e+000
 bb_par.l5b1_1    0 3.1443191285114379e-002  3.1328482481451932e-002  2.2065974179999999e+000  2.6521342440000000e-005  1.0000000000000000e+000
 bb_ho5b1_0         15 2.9500000000000001e-004  0.0000000000000000e+000  9.1249858139999997e-007 -1.3528401410000000e-006
  5.0034904287164825e-005 -9.5933702435896557e-008  2.2442853989596686e-003  5.0210518708273642e-005  7.5281139492566265e-007
  2.2365333553914309e-003 -1.6633936155651148e-009 -1.5308147527101169e-009  7.3429015665098211e-010 -6.5172371426280837e-009  1.0000000000000000e+000
 bb_par.r5b1_1    0 3.1441770046453613e-002  3.1339744553102268e-002 -2.2065955920000002e+000 -2.9226727900000001e-005  1.0000000000000000e+000
 bb_par.r5b1_2    0 1.2561839670835107e-001  1.2519708458125575e-001 -4.4131920969999996e+000 -5.7100763079999998e-005  1.0000000000000000e+000
 bb_par.r5b1_3    0 2.8257991488973672e-001  2.8162223060384217e-001 -6.6197886019999999e+000 -8.4974798249999999e-005  1.0000000000000000e+000
 bb_par.r5b1_4    0 5.0232632459220838e-001  5.0061518261964988e-001 -8.8263851080000002e+000 -1.1284883340000000e-004  1.0000000000000000e+000
 bb_par.r5b1_5    0 7.8485762581413310e-001  7.8217594062696949e-001 -11.032981610000000e+000 -1.4072286860000000e-004  1.0000000000000000e+000
 bb_par.r5b1_6    0 1.1301738185477808e+000  1.1263045046311166e+000 -13.239578119999999e+000 -1.6859690380000001e-004  1.0000000000000000e+000
 bb_par.r5b1_7    0 1.4489267054992951e+000  1.6256593064129110e+000 -15.448509860000000e+000 -2.0232402110000001e-004  1.0000000000000000e+000
 bb_par.r5b1_8    0 1.5337310327716311e+000  2.5684627649943046e+000 -17.708469149999999e+000 -2.5412074129999999e-004  1.0000000000000000e+000
 bb_par.r5b1_9    0 1.4337954001193285e+000  4.0956526301219460e+000 -20.081349490000001e+000 -3.2074327350000001e-004  1.0000000000000000e+000
 bb_par.r5b1_10   0 1.4209078897413632e+000  5.6532311753224995e+000 -22.263216289999999e+000 -3.7671041900000000e-004  1.0000000000000000e+000
 bb_par.r5b1_11   0 1.6715424781841688e+000  6.3625426973680561e+000 -23.802278410000000e+000 -3.9954697059999998e-004  1.0000000000000000e+000
 bb_par.r5b1_12   0 2.1339837792041614e+000  6.4329000697014500e+000 -24.942846100000001e+000 -4.0165857220000000e-004  1.0000000000000000e+000
 bb_par.r5b1_13   0 3.0623680329892764e+000  5.4984143654307989e+000 -25.557506950000001e+000 -3.7125319360000001e-004  1.0000000000000000e+000
 bb_par.r5b1_14   0 4.5791197430480350e+000  4.0369413656180351e+000 -25.900526500000002e+000 -3.1801704040000000e-004  1.0000000000000000e+000
 bb_par.r5b1_15   0 6.0315601950176525e+000  3.0020601351501797e+000 -26.151511249999999e+000 -2.7412950559999998e-004  1.0000000000000000e+000
 bb_par.r5b1_16   0 6.5282772069516630e+000  2.5955338516801936e+000 -26.017086140000000e+000 -2.5475781969999998e-004  1.0000000000000000e+000
 bb_par.r5b1_17   0 6.2474064986036115e+000  2.5238227214811628e+000 -25.456456620000001e+000 -2.5106548810000000e-004  1.0000000000000000e+000
 bb_par.r5b1_18   0 5.9543265061042305e+000  2.4605464708370244e+000 -24.342545810000001e+000 -2.4774777410000001e-004  1.0000000000000000e+000
 bb_par.l1b1_18   0 2.4453915906392605e+000  5.9246156480209136e+000  1.7852829300000000e-004  24.263057230000001e+000  1.0000000000000000e+000
 bb_par.l1b1_17   0 2.5082770622259680e+000  6.2162233913155216e+000  1.8091900779999999e-004  25.348122539999999e+000  1.0000000000000000e+000
 bb_par.l1b1_16   0 2.5795454446451664e+000  6.4956829815813499e+000  1.8357953630000000e-004  25.913897739999999e+000  1.0000000000000000e+000
 bb_par.l1b1_15   0 2.9835664390021805e+000  6.0014394725584257e+000  1.9753296239999999e-004  26.060380960000000e+000  1.0000000000000000e+000
 bb_par.l1b1_14   0 4.0120712843986572e+000  4.5562487911792848e+000  2.2914410270000001e-004  25.824147360000001e+000  1.0000000000000000e+000
 bb_par.l1b1_13   0 5.4645395486571013e+000  3.0470700172890228e+000  2.6748880480000000e-004  25.496763150000000e+000  1.0000000000000000e+000
 bb_par.l1b1_12   0 6.3932669995083042e+000  2.1233199832378067e+000  2.8938769619999999e-004  24.897105130000000e+000  1.0000000000000000e+000
 bb_par.l1b1_11   0 6.3233421409104755e+000  1.6631850636522600e+000  2.8786307399999999e-004  23.771061750000001e+000  1.0000000000000000e+000
 bb_par.l1b1_10   0 5.6183998932712074e+000  1.4137984943264161e+000  2.7140912779999998e-004  22.246431520000002e+000  1.0000000000000000e+000
 bb_par.l1b1_9    0 4.0704172612716576e+000  1.4266153235010426e+000  2.3108939760000001e-004  20.078973739999999e+000  1.0000000000000000e+000
 bb_par.l1b1_8    0 2.5526364255504679e+000  1.5260440171049194e+000  1.8309404000000000e-004  17.708622380000001e+000  1.0000000000000000e+000
 bb_par.l1b1_7    0 1.6156415748136290e+000  1.4416591967273391e+000  1.4577796230000000e-004  15.448658719999999e+000  1.0000000000000000e+000
 bb_par.l1b1_6    0 1.1193631588715744e+000  1.1245006729571665e+000  1.2147743290000000e-004  13.239709520000000e+000  1.0000000000000000e+000
 bb_par.l1b1_5    0 7.7735471007505763e-001  7.8091381717896147e-001  1.0139282900000000e-004  11.033091040000000e+000  1.0000000000000000e+000
 bb_par.l1b1_4    0 4.9752879820584245e-001  4.9979834463684619e-001  8.1308225150000004e-005  8.8264725550000005e+000  1.0000000000000000e+000
 bb_par.l1b1_3    0 2.7988542327175636e-001  2.8115425533633054e-001  6.1223621290000004e-005  6.6198540719999999e+000  1.0000000000000000e+000
 bb_par.l1b1_2    0 1.2442458527275180e-001  1.2498154927712136e-001  4.1139017420000000e-005  4.4132355900000002e+000  1.0000000000000000e+000
 bb_par.l1b1_1    0 3.1146284209145926e-002  3.1280226459102507e-002  2.1054413559999999e-005  2.2066171059999999e+000  1.0000000000000000e+000
 bb_ho1b1_0         15 2.9500000000000001e-004  1.5700000000000001e+000  9.6983435799999992e-007 -1.3760678740000000e-006
  5.0520080285947416e-005 -6.0102042820216679e-007  2.2227616225043104e-003  5.0286882391145739e-005  7.7036976500561835e-007
  2.2330904282531743e-003 -3.6528061007530751e-009  2.6610093044576255e-008  3.6386713069639950e-008  1.1594620089159194e-007  1.0000000000000000e+000
 bb_par.r1b1_1    0 3.1137292902883109e-002  3.1291730563730337e-002 -1.9114794169999999e-005 -2.2066198579999998e+000  1.0000000000000000e+000
 bb_par.r1b1_2    0 1.2440660266024108e-001  1.2500455748637873e-001 -3.9199398030000000e-005 -4.4132383409999996e+000  1.0000000000000000e+000
 bb_par.r1b1_3    0 2.7985844935271914e-001  2.8118876765036310e-001 -5.9284001890000001e-005 -6.6198568240000002e+000  1.0000000000000000e+000
 bb_par.r1b1_4    0 4.9749283298064084e-001  4.9984436105741470e-001 -7.9368605759999998e-005 -8.8264753070000008e+000  1.0000000000000000e+000
 bb_par.r1b1_5    0 7.7730975354344767e-001  7.8097133770244376e-001 -9.9453209619999999e-005 -11.033093790000001e+000  1.0000000000000000e+000
 bb_par.r1b1_6    0 1.1193092110475640e+000  1.1245696975951323e+000 -1.1953781350000001e-004 -13.239712270000000e+000  1.0000000000000000e+000
 bb_par.r1b1_7    0 1.4350019289418381e+000  1.6231550848947471e+000 -1.3551144120000001e-004 -15.448661970000000e+000  1.0000000000000000e+000
 bb_par.r1b1_8    0 1.5189954927064870e+000  2.5645057164849878e+000 -1.3956999820000001e-004 -17.708627610000001e+000  1.0000000000000000e+000
 bb_par.r1b1_9    0 1.4200244002253559e+000  4.0893420699705363e+000 -1.3509844260000000e-004 -20.078982109999998e+000  1.0000000000000000e+000
 bb_par.r1b1_10   0 1.4072651096279496e+000  5.6445202819752645e+000 -1.3464586309999999e-004 -22.246442349999999e+000  1.0000000000000000e+000
 bb_par.r1b1_11   0 1.6554976228443443e+000  6.3527390178973215e+000 -1.4618400250000001e-004 -23.771072860000000e+000  1.0000000000000000e+000
 bb_par.r1b1_12   0 2.1135042658473391e+000  6.4229885352324203e+000 -1.6529777280000000e-004 -24.897114970000001e+000  1.0000000000000000e+000
 bb_par.r1b1_13   0 3.0329827718413100e+000  5.4899438273772336e+000 -1.9811631760000001e-004 -25.496768419999999e+000  1.0000000000000000e+000
 bb_par.r1b1_14   0 4.5351834278253023e+000  4.0307240578574195e+000 -2.4233517500000000e-004 -25.824145160000000e+000  1.0000000000000000e+000
 bb_par.r1b1_15   0 5.9736913201220814e+000  2.9974387026659750e+000 -2.7818854729999998e-004 -26.060373530000000e+000  1.0000000000000000e+000
 bb_par.r1b1_16   0 6.4656478131346748e+000  2.5915403784956927e+000 -2.8948047600000000e-004 -25.913891990000000e+000  1.0000000000000000e+000
 bb_par.r1b1_17   0 6.1874779676075446e+000  2.5199418460775598e+000 -2.8325232359999999e-004 -25.348123850000000e+000  1.0000000000000000e+000
 bb_par.r1b1_18   0 5.8972159774117294e+000  2.4567656757803236e+000 -2.7659780290000002e-004 -24.263065749999999e+000  1.0000000000000000e+000
```

This should make the conversion and comparisons a bit more convenient.

Unless there are comments, I'll merge it this afternoon.

**Pull request merged**
