### PR TITLE
Round properly when reading fort.13

### PR DESCRIPTION
**Pull request by kyrsjo**
No tests needed to be changed - seems that gfortran (which I was using for the testing) was doing the right thing when reading!

Note: Should also be tested with ifort and nagfor (ideally before and after).

Tests using fort.13:
```
SixTest $ find . -name "fort.13"
./javier_bignpart/fort.13
./rfMultipoles_3rdOrder/fort.13
./rfMultipoles_2ndOrder/fort.13
./scatter_bbelastic/fort.13
./beam-HO_4D-newstyle-loadParticles/fort.13
./thick6ddynk/fort.13
./beam-HO_6D-simple-newstyle-coupling/fort.13
./rfMultipoles_4thOrder/fort.13
```

### CODE REVIEW

**Comment by kyrsjo** [comment]
Note that the tests `javier_bignpart` and `beam-HO_6D-simple-newstyle-coupling` needs to be tested with BIGNPART (etc.).

**Comment by JamesMolson** [comment]
ifort:

```
The following tests FAILED:
	 16 - dipedge (Failed)
	 43 - dump7_fma_thin4d (Failed)
	 70 - rfMultipoles_2ndOrder (Failed)
	 71 - rfMultipoles_3rdOrder (Failed)
	 72 - rfMultipoles_4thOrder (Failed)
	 74 - scatter_bbelastic (Failed)
```

**Comment by JamesMolson** [comment]
nagfor:
```
The following tests FAILED:
	 16 - dipedge (Failed)
	 71 - rfMultipoles_3rdOrder (Failed)
	 72 - rfMultipoles_4thOrder (Failed)
```

**Comment by JamesMolson** [comment]
um, ignore all that, seems I hit my afs quota limit

**Pull request merged**
