### PR TITLE
regenerate input in build directory if source changed

### PR DESCRIPTION
**Pull request by rdemaria**

### CODE REVIEW

**Comment by vkbo** [comment]
This PR is incomplete and should not have been merged yet.

**Comment by rdemaria** [comment]
Sorry, my bad. Do you refer to  eliminate run_prepro?

**Comment by vkbo** [comment]
No, to that it ignores changes to include files. Trying to fix it now ...

**Comment by vkbo** [comment]
Since CMake does not resolve dependencies well here, I don't think there is any other way than to either:
1. Make all files depend on all includes, which both slows down the build process and results in a full rebuild anyway when an included file is change, or
2. Manually or with a script resolve these dependencies and add them to the relevant files.

**Comment by rdemaria** [comment]
I would try with a  script to resolve dependencies, e.g. 

```
awk  '/#include/ {print $2}' track_thin.f90 | sort -u
```

Can we use awk and sort also in msys, right?

**Pull request merged**
