### PR TITLE
Code comments are not version control.

### PR DESCRIPTION
**Pull request by JamesMolson**
See issue #114

### CODE REVIEW

**Comment by kyrsjo** [comment]
Testing (compiling them) and reviewing (reading through the diff) the changes. Unless someone is strongly opposed, I will merge it later today.

**Comment by kyrsjo** [comment]
Let's also see if there are other similar stuff that can be cleansed...

**Comment by JamesMolson** [comment]
Other .s files have the same issue going on but I've not purged them yet.

**Comment by kyrsjo** [comment]
You mean dabnew.s? plato.s (the FMA library) should be fine.

**Comment by kyrsjo** [comment]
Hi can you bump the date in the +cd version block to TODAY, and add your name to the +cd license block? Once this I've done, I'll merge this + #118 #116 + close #119

**Comment by JamesMolson** [comment]
You can close #13 too.

Are we sure the test suite covers the functions in dabnew.s ?

**Comment by kyrsjo** [comment]
Hi,
I'm pretty sure they do not. Also, these files we pretty much never need to touch, so there may not be any very good reason to remove this stuff.

And urk. I did not realize, but you started from an older version; this makes the conflict when you change the license block (and is the reason why we only change the licence/date block at the last moment before merging.

So: Maybe you could do a git reset of this branch back to before 042472e , then force push to get rid of that commit on GitHub, then merge the current upstream/master into the branch, then change license block? For the `lielib.s`, I reviewed the changes manually, for `dabnew` I see that you killed two text comments as well as the old commented-out code.

I would actually really like to look through the `sixtrack.s` changes manually before merging, to look for other deleted comment blocks.

**Comment by kyrsjo** [comment]
Thanks for the rollback!

**Pull request merged**
