### PR TITLE
Solenoid fix

### PR DESCRIPTION
**Pull request by jodander**
Found a bug in the Solenoid element that Tobias then identified and I wrote a quick fix for. Basically the Solenoid uses a temporary variable temptr(6) that is uninitialized on the first turn resulting in a minor but detectable difference. Switching the order the variables are updated fixes this and should have no impact on any other element.

Fix includes:
- Moving two lines of code
- Updating the orbit6d-element-solenoid test case canonical files

The branch passes all fast tests except for the 'elens' tests.

### CODE REVIEW

**Comment by rdemaria** [comment]
Can you issue a pull requests for the fix? I guess only the solenoid  test
will be affected, right?

**Comment by tpersson** [comment]
There is already a PR and the tests are updated. However, I can still not approve it..
________________________________

**Comment by tpersson** [comment]
Or to be more precise, I can approve but not click merge..
________________________________
From: Tobias Hakan Bjorn Persson
Sent: 23 August 2018 12:17
To: SixTrack/SixTrack; SixTrack/SixTrack
Cc: Comment
Subject: RE: [SixTrack/SixTrack] Solenoid fix (#635)

There is already a PR and the tests are updated. However, I can still not approve it..
________________________________

**Comment by vkbo** [comment]
@jodander Could you please add the bug fix to the top of the CHANGELOG.md file above the last release? Also, feel free to add your name to the author list in README.md.

Since this is a physics fix, we will need to build all the BOINC executables again and run the tests before we merge. I'll start on this now.

**Comment by rdemaria** [comment]
@tpersson , the merge button appears after the circleci pass the test and the PR is approved by review. For instance you should see the merge button now.

**Comment by vkbo** [comment]
The list is in alphabetical order, but I updated it. Thanks!

Will merge as soon as the executables have been re-built and tests passed.

**Pull request merged**
