### PR TITLE
Detect missing xstr in BEAM block

### PR DESCRIPTION
**Pull request by kyrsjo**
If missing, print WARNING and set xstr=xang.

### CODE REVIEW

**Comment by kyrsjo** [comment]
I tested it using `SixTest/javier`, where the xstr is present. Only this and `javier_bignpart` actually contains the 2nd line of the BEAM block.

**Comment by kyrsjo** [comment]
This fixes #126

**Comment by kyrsjo** [comment]
@rdemaria : Javier and I agree that we should STOP and print error message if old file format is encountered. Agreed?

**Comment by rdemaria** [comment]
No, I prefer the old style passes with warning because of many old tools...

**Comment by kyrsjo** [comment]
OK, will do.

By the way, I have a small doubt about the manual; it says:
"Angle of the position of the slices in the boosted frame [rad] (i.e. X = Z sin(xstr ) cos(xplane),
Y = sin(xstr ) cos(xplane) ). In absence of crabbing user should make sure xstr=xang; in case
the xstr flag is not set then xstr=xang is assumed and a warning is printed (since version 4.5.45)."

I guess that should really be not just X=Z * sin etc., but also Y = Z * sin etc.?

**Comment by rdemaria** [comment]
I guess I forgot a Z...

On Mon, Dec 19, 2016 at 1:17 PM, Kyrre Ness Sjøbæk <notifications@github.com

**Comment by kyrsjo** [comment]
Can you push to my branch? TIL...

**Comment by kyrsjo** [comment]
Ah, it's the "allow edits from maintainers" setting. Huh, TIL again.

**Comment by rdemaria** [comment]
What is til?

**Comment by kyrsjo** [comment]
TIL = Today I Learned :)

**Pull request merged**
