### PR TITLE
Change aperture tilt to degree 

### PR DESCRIPTION
**Pull request by tpersson**
I did the conversion in the input parsing. I saw that at some other places it is done for each particle. Is there a reason for that?

### CODE REVIEW

**Comment by amereghe** [comment]
@tpersson thanks for the modifications!
I don't get your question - could you point me to the concerned lines?

**Comment by tpersson** [comment]
@amereghe It is all fine, my mistake it looks like it is all in the initialization.

**Comment by rdemaria** [comment]
I would make the conversion at initialize elements

**Comment by amereghe** [comment]
@rdemaria it is not needed - the code is already in good shape :D

**Comment by vkbo** [comment]
@rdemaria One check seems to be hanging. Can you use the admin privileges to override and merge? It is ready.

**Comment by amereghe** [comment]
@vkbo which test was failing and where?

**Comment by tpersson** [comment]
Tried to add another commit but still not working. I have no idea what is going wrong. The tests pass but still no report.

**Comment by vkbo** [comment]
Riccardo should be able to override. I do this on my own repository sometimes when I have the same issue, but let me change policy back and forth and do it that way.

**Pull request merged**
