### PR TITLE
Sixtest thick6d

### PR DESCRIPTION
**Pull request by kyrsjo**
Note that the "single element" version doesn't really work - see the fort.6.canonical. It crashes with the error message:
```
-----------------------------------------------------------------------------------------------------------------------------------

         OOOOOOOOOOOOOOOOOOOOO
         OO                 OO
         OO  PREPROCESSING  OO
         OO                 OO
         OOOOOOOOOOOOOOOOOOOOO

-----------------------------------------------------------------------------------------------------------------------------------


         STRUCTURE INPUT FILE HAS -THICK- LINEAR ELEMENTS


    ---- ENTRY CLORB ----/DPP= 0.00000 /CLOX/       NaN       NaN /CLOY/       NaN       NaN /ITERAT.=  2/ ACCURACY= 0.000000D+00
    ---- ENTRY CLORB ----/DPP= 0.00000 /CLOX/       NaN       NaN /CLOY/       NaN       NaN /ITERAT.=  2/ ACCURACY= 0.000000D+00
    ---- ENTRY CLORB ----/DPP= 0.00000 /CLOX/       NaN       NaN /CLOY/       NaN       NaN /ITERAT.=  2/ ACCURACY= 0.000000D+00
    ---- ENTRY CLORB ----/DPP= 0.00000 /CLOX/       NaN       NaN /CLOY/       NaN       NaN /ITERAT.=  2/ ACCURACY= 0.000000D+00
------------------------------------------------------------------------------------------------------------------------------------
    ---- ENTRY LINOPT ----



         ++++++++++++++++++++++++
         +++++ERROR DETECTED+++++
         ++++++++++++++++++++++++
         RUN TERMINATED ABNORMALLY !!!


         AMPLITUDES EXCEED THE MAXIMUM VALUES IN UMLAUF
```

Seems something is fishy with how the closed orbit search is initialized? Or maybe I just did a stupid mistake...

### CODE REVIEW

**Comment by kyrsjo** [comment]
MadX commands to produce the fort.2:
```
d: drift,l=1.0;
qf: quadrupole,l=0.5,k1=0.2;
qd: quadrupole,l=0.5,k1=-0.2;
fodo: line=(qf,5*(D),qd,qd,5*(d),qf);
beam;
use,sequence=fodo;
twiss;
sixtrack;
```

FODO based on presentation by Volker Zimmerman:
http://ziemann.web.cern.ch/ziemann/teaching/ht08/081030-madx.pdf

**Comment by rdemaria** [comment]
What is blocksin?

**Comment by kyrsjo** [comment]
blocksin is the same as blocks, except it's just the input files. This pattern is used for all the SixTest tests - there is a folder "testname" and then there is "testnamein"

**Comment by kyrsjo** [comment]
Discussed with Riccardo, there seems to be a bug in the closed orbit calculation for thick quadrupoles that are not in a BLOC.

Merging the tests - including the failing one - and putting a bug in the issue tracker...

**Pull request merged**
