### PR TITLE
Fix beambeam boost

### LINKED ISSUE #260: Bug in Beam-Beam inverse boost
Wrong code

    *FOX    TRACK(2)=(TRACK(2)+CALPHA*SPHI*H1)*CPHI ;
    *FOX    TRACK(4)=(TRACK(4)+SALPHA*SPHI*H1)*CPHI ;

Fixed code

    *FOX    TRACK(2)=(TRACK(2)*CPHI+CALPHA*TPHI*H1) ;
    *FOX    TRACK(4)=(TRACK(4)*CPHI+SALPHA*TPHI*H1) ;

See eq. 2.39 in https://cds.cern.ch/record/425950/files/lhc-project-report-369.pdf. The code is supposed to invert the equation for px and py. 

Reported by Giovanni Iadarola @giadarol

### PR DESCRIPTION
**Pull request by rdemaria**
Fixes #260

### CODE REVIEW

**Comment by rdemaria** [comment]
Rerunning the test suite...

**Comment by kyrsjo** [comment]
Push it to CDASH!

**Comment by kyrsjo** [comment]
Hmm.. I see your act of civil disobedience with the tabs and spaces in `SixTest/CMakeList.txt`. Personally, I approve... @JamesMolson ?

**Comment by rdemaria** [comment]
My editor screams when there are tabs, spaces before newline and my
terminal introduces bugs when lines are longer than 79 character...

**Comment by kyrsjo** [comment]
My editor really fights me when I try to use tabs instead of spaces. The only way to force it to write tabs is to find a tab and copy-paste it. It will however keep using tabs on consequent lines... Until it finds at { or }.

It's probably in the setup somewhere... `M-x heathen-mode` ?

**Comment by JamesMolson** [comment]
Then your editors/terminal are broken/misconfigured, fix them or use a better one :p spaces are going to end up as an unaligned mess like in sixtrack.s but I guess @rdemaria is in charge!

**Comment by kyrsjo** [comment]
Confirmed working tests:
* FAST with standard build
* FAST with standard build / ifort
* FAST with STF
* FAST with BOINC-type build
* MEDIUM with standard build

Nothing was found to be failing. The two slow tests, prob1 and prob3, does not include 6D beam lenses.

**Comment by kyrsjo** [comment]
Correction: `beam-HO_6D-simple` fails with BOINC, because Sixin.zip is missing. I've fixed that.

Also, `CheckTestInput_BOINC` did not fail, but gave a warning:
`WARNING: No Sixin.zip found in 'beam-HO_6D-simple'`
It will only give an error if the Sixin.zip is there, but in an inconsistent state. I guess that's OK? I'll see if I can find a way to have CTest report a WARNING that is not an ERROR.

Further: extra_checks.txt was mising from the same test, causing the dump files to be ignored. Fixed.

Riccardo: Could you please write a statement to go with the merge? Something like "Fixed trigonometric expression in 6D beam-beam lens"?

**Comment by rdemaria** [comment]
Fixes bug in 6D beam beam lens (inverse of the boost (see #260)

**Comment by JamesMolson** [comment]
This broke the javier_bignpart test

http://abp-cdash.web.cern.ch/abp-cdash/testDetails.php?test=189170&build=37956

**Comment by rdemaria** [comment]
Thanks! I thought I have updated all the tests that were supposed to change. I cannot fix it today, I will try in the following days...

**Pull request merged**
