### PR TITLE
Integrate NAFF library for FMA

### PR DESCRIPTION
**Pull request by kyrsjo**
Integrate the NAFF library ( https://github.com/skostogl/NAFF_cpp , written by Sofia Kostoglou @skostogl ) as a possible method for FMA analysis.

Some testing, documentation, and fixing of corner cases still remain.

### CODE REVIEW

**Comment by kyrsjo** [comment]
TODO:
* Sofia makes pull request with her fixes into this branch (these disables the non-functional array length fixes)
* Kyrre passes normalization flag from sixtrack.s -> the C++ wrapper, Sofia handles it correctly in NAFF
* Miriam handles correct FFT in plato in case of non-normalized coordinates. To be done once NAFF is complete, in a new branch off from master

**Comment by kyrsjo** [comment]
Hi @skostogl , have you changed anything in sixtrack.s? If not I would like to merge the current master master into this branch (since the merging of #312 changed some lines that I also changed in this branch - it's mostly just whitespace tough). If you have changed something, I'll just wait for you to merge that first.

**Comment by skostogl** [comment]
Hello,

No I haven't touched sixtrack.s only the NAFF codes, please go ahead with the merging

Cheers
Sofia

18 Αυγ 2017, 10:08 μμ, ο/η Kyrre Ness Sjøbæk <notifications@github.com<mailto:notifications@github.com>> έγραψε:


Hi @skostogl<https://github.com/skostogl> , have you changed anything in sixtrack.s? If not I would like to merge the current master master into this branch (since the merging of #312<https://github.com/SixTrack/SixTrack/pull/312> changed some lines that I also changed in this branch - it's mostly just whitespace tough). If you have changed something, I'll just wait for you to merge that first.

**Comment by kyrsjo** [comment]
TODO: Pass the NAFF wrapper a flag (1/2/3) for which plane we are looking at. It should use different windows etc. for that; plus there is also the 1-q for the third plane that needs to be handled 100% correctly.

**Comment by kyrsjo** [comment]
Hmm, FYI the NAFF library crashes with a segfault when I called `get_f1` such that both arguments `(data, data_prime)` had length 0...

**Comment by skostogl** [comment]
Hello,

You mean when the input arrays have zero length?

21 Αυγ 2017, 4:39 μμ, ο/η Kyrre Ness Sjøbæk <notifications@github.com<mailto:notifications@github.com>> έγραψε:


Hmm, FYI the NAFF library crashes with a segfault when I called get_f1 such that both arguments (data, data_prime) had length 0...

**Comment by kyrsjo** [comment]
OK, now the results are reasonable (again). It would probably be a good idea to define the `xyzv` and `nxyzv` arrays as turn,particle,plane or `turn,plane,particle`, not `particle,turn,plane` (where the first index is the fastest).

**Comment by skostogl** [comment]
Latest changes:
- The normalization flag is used to determine whether the input array should only be x (physical coordinates) or complex (x, px) (normalized)
- The "plane" flag is used to determine the order of the Hann window (2nd order for Qx, Qy and 1st order for Qs)
- In case both x, xp are empty arrays it throws an error instead of seg fault

**Comment by kyrsjo** [comment]
Great! What is left then? Documentation? Anything else? Or are you basically now just waiting for Miriam and me to add first/last turn to the input file so that you can do the moving window scan?

**Comment by skostogl** [comment]
I think that these were all the things that we discussed. The next step is the moving window FFT.

**Comment by skostogl** [comment]
Also, thanks for fixing the fma_sixtrack.canonical for sixtest, i forgot to change the file

**Comment by kyrsjo** [comment]
TODO:
- [ ] User manual, add description of NAFF method to FMA section (the table); reference paper/note for the library, point out that NAFF must be enabled at build time and reference the build manual. -> Sofia
- [ ] Build manual: Add description of how to build NAFF library and what are its dependencies
- [ ] Add Sofia to list of authors in sixtrack.s and manual -> Sofia
- [ ] Bump version number & date -> Kyrre

**Comment by kyrsjo** [comment]
We're done; I'm bumping the version number and merging now.

**Comment by kyrsjo** [comment]
Effect of different machines (and thus different library version) - canonical (right) is from CENTOS 7 as produced by Sofia; current (left) is from Fedora 25 as produced by Kyrre:
naff-diff
Sofia also cloned, recompiled and tested the version https://github.com/SixTrack/SixTrack/pull/296/commits/96de9de6572f27f6950de1a552c7f982d736c10f (same as Kyrre used to produce this screenshot) with CentOS7 just to make sure that it was not a mistake in which canonical was uploaded; on CentOS7 the test was still claiming PASS.

It is interesting that it is only the "real coordinates" case that is different; the "normalized coordinates" case is the same.

**Pull request merged**
