### PR TITLE
Single diffraction differential cross section typo fix

### PR DESCRIPTION
**Pull request by JamesMolson**
changes 26 to 36.

### CODE REVIEW

**Comment by kyrsjo** [comment]
Since this changes physics, you should bump the version number and time of modification before the pull is accepted. Please do so right before it is accepted, so we don't have anyone else sneaking in before you :)

**Comment by kyrsjo** [comment]
This pull should fix #55

**Comment by JamesMolson** [comment]
What exactly need changing with regards to version numbers (which files) ?

**Comment by kyrsjo** [comment]
It's all in The File, aka sixtrack.s. It's one of the first lines!

**Comment by JamesMolson** [comment]
I already updated it :)

**Comment by kyrsjo** [comment]
Ah, somehow I didn't see it in the app... Anyway, since everyone agrees, I'll merge it!

Thanks a lot, and sorry for taking forever to respond; I was (mostly) AFK.

**Pull request merged**
