### PR TITLE
Fix tests

### LINKED ISSUE #189: Canonicals missing for test `elensidealthin6d_DYNK`
All canonicals seems to be missing for this test.

Miriam: Could you please checkout the newest master on Linux and create a new branch from there, do a standard build (just run ./cmake_six without any arguments - it should give you a gfortran build), run this test with SixTest (run_pro), rename the fort.10 etc. + your extra_checks to .canonical as usual, commit the files, and make a PR? This should be a quick fix...

If you have canonicals already, could you please just commit these to a new branch off off master?

Cheers,
Kyrre

### PR DESCRIPTION
**Pull request by kyrsjo**
* Delete surplus inputs in wire tests as agreed with Miriam
 * Fix #189 (TODO)

### CODE REVIEW

**Comment by kyrsjo** [comment]
Done?

**Comment by JamesMolson** [comment]
extra_inputs.txt on  elensidealthin6d_DYNK ?

**Comment by mfittere** [comment]
Wire tests still pass? Just to check that I didn't do any mistake.

**Comment by kyrsjo** [comment]
Tests pass; no extra_inputs are needed? I'll double-check that everything passes on another machine...

**Comment by JamesMolson** [comment]
I meant extra_outputs.txt for HEL_DUMP_1.canonical  etc

**Comment by mfittere** [comment]
If one wire test pass without the fort.13 all the rest will pass. So it is fine. Thanks for checking!

**Comment by kyrsjo** [comment]
It's there, called `extra_checks.txt`.

**Comment by kyrsjo** [comment]
I checked in my 32-bit Linux VM, all tests pass.

One more thing to do: STF tests!

**Comment by JamesMolson** [comment]
I see now. I've run it and all the tests pass (wire and this new one).

**Comment by kyrsjo** [comment]
FYI, at least with the STF version of SixTrack I have these warnings when running the wire tests:
```
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
```

**Comment by mfittere** [comment]
Yes, I know ... Let's ignore them for the moment.

**Pull request merged**
