### PR TITLE
Convert common blocks to modules

### PR DESCRIPTION
**Pull request by kyrsjo**
This patch converts several of the big +cd blocks to modules, namely `parpro`, `common`, `commonmn`, and `commons`. Furthermore it removes `DATAMODS`, as this functionality (`allocate_thickarrays`) is now included in the new modules and always enabled. It also fixes a bug where part of fort.95 would be read twice when datamods is disabled (including once with the wrong format), and not at all when it is enabled.

This is a preparation for making the big arrays become dynamically allocated.

### CODE REVIEW

**Comment by kyrsjo** [comment]
Hi, has anyone looked at this?

**Comment by rdemaria** [comment]
If one would have been creative with ad-hoc definitions and astuce blocks, willingly or unwillingly re-scoping variables, would your changes affect the semantic?

**Comment by JamesMolson** [comment]
Collimation does not build with this

**Comment by JamesMolson** [comment]
Everything now seems to be working!

**Pull request merged**
